apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: ld
type: Opaque
stringData:
  JWT_SECRET: "supersecret_jwt_key_change_in_production"
  AUTH_SERVICE_URL: "http://auth-svc:3001"
  USER_SERVICE_URL: "http://user-svc:3002"
  TRAINING_SERVICE_URL: "http://training-svc:3003"
  ATTENDANCE_SERVICE_URL: "http://attendance-svc:3004"
  