apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment 
  namespace: ld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ld
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ld
    spec:
      containers:
        - name: user-cont
          image: chandu554/user_lb_image:latest
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: PORT
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"